#!/bin/sh
set -e

case "$1" in
  configure)
    if ! getent passwd chan-gateway-devserver-control >/dev/null; then
      adduser --system --no-create-home --group chan-gateway-devserver-control
    fi
    install -d -m 0751 -o root -g root /etc/chan-gateway
    if [ -f /etc/chan-gateway/domain.env ]; then
      chown root:root /etc/chan-gateway/domain.env
      chmod 0644 /etc/chan-gateway/domain.env
    fi
    if [ -f /etc/chan-gateway/devserver-control.env ]; then
      chown root:chan-gateway-devserver-control /etc/chan-gateway/devserver-control.env
      chmod 0640 /etc/chan-gateway/devserver-control.env
    fi
    ;;
esac

#DEBHELPER#

exit 0
