#!/usr/bin/env bash
# Generate /etc/chan-gateway/{profile,identity,workspace-proxy}.env on a
# host where the three .debs are already installed.
#
# Usage:
#   sudo ./configure.sh
#
# Prompts for the values that aren't safely defaultable (Postgres
# password, GitHub OAuth credentials, public base URL). Generates a
# PROFILE_AUTH_TOKEN and reuses it across the three files where
# required. Backs up any existing env files before overwriting.

set -euo pipefail

if [[ $EUID -ne 0 ]]; then
    echo "error: run as root (sudo $0)" >&2
    exit 1
fi

if ! getent passwd chan-gateway >/dev/null; then
    echo "error: chan-gateway user is missing. Install the .debs first." >&2
    exit 1
fi

read -rp "Postgres user [chan]: " PG_USER
PG_USER=${PG_USER:-chan}

read -rsp "Postgres password for ${PG_USER}: " PG_PASS; echo
[[ -n "$PG_PASS" ]] || { echo "password required" >&2; exit 1; }

read -rp "Postgres database [chan_gateway]: " PG_DB
PG_DB=${PG_DB:-chan_gateway}

# Single source for the public hostnames. identity and workspace-proxy
# derive id.<domain>, workspace.<domain>, and *.workspace.<domain> from
# this base, so they cannot drift.
read -rp "Base domain [chan.app]: " CHAN_DOMAIN
CHAN_DOMAIN=${CHAN_DOMAIN:-chan.app}
CHAN_DOMAIN=${CHAN_DOMAIN#.}; CHAN_DOMAIN=${CHAN_DOMAIN%.}

read -rp "Public URL scheme [https]: " PUBLIC_SCHEME
PUBLIC_SCHEME=${PUBLIC_SCHEME:-https}
[[ "$PUBLIC_SCHEME" == "http" || "$PUBLIC_SCHEME" == "https" ]] || {
    echo "error: scheme must be http or https" >&2; exit 1;
}
# Derived id origin, used only for the callback-URL reminder below;
# identity-service itself derives BASE_URL from CHAN_DOMAIN.
ID_URL="${PUBLIC_SCHEME}://id.${CHAN_DOMAIN}"

echo
echo "Configure at least one OAuth provider. Press Enter to skip any."
echo

prompt_provider() {
    # bash 4.3+ namerefs; safer than `eval` because the value never
    # passes through the shell parser.
    local name=$1
    local -n out_id=$2
    local -n out_secret=$3
    local id="" secret=""
    read -rp "$name OAuth Client ID (empty to skip): " id
    if [[ -n "$id" ]]; then
        read -rsp "$name OAuth Client Secret: " secret; echo
        if [[ -z "$secret" ]]; then
            echo "  -> ${name} secret was empty; skipping ${name}"
            id=""
        fi
    fi
    out_id="$id"
    out_secret="$secret"
}

prompt_provider "GitHub"     GH_ID  GH_SECRET
prompt_provider "Google"     GOOG_ID GOOG_SECRET
prompt_provider "GitLab"     GL_ID  GL_SECRET

if [[ -z "$GH_ID" && -z "$GOOG_ID" && -z "$GL_ID" ]]; then
    echo "error: at least one provider is required" >&2
    exit 1
fi

emit_provider_env() {
    local prefix=$1 id=$2 secret=$3
    if [[ -n "$id" ]]; then
        printf '%s_CLIENT_ID=%s\n%s_CLIENT_SECRET=%s\n' \
            "$prefix" "$id" "$prefix" "$secret"
    fi
}

# URL-encode the password so special characters don't break DATABASE_URL.
PG_PASS_ENC=$(python3 -c 'import sys,urllib.parse; print(urllib.parse.quote(sys.argv[1], safe=""))' "$PG_PASS")
DATABASE_URL="postgres://${PG_USER}:${PG_PASS_ENC}@127.0.0.1/${PG_DB}"

PROFILE_AUTH_TOKEN=$(openssl rand -hex 32)
REGISTRY_TOKEN=$(openssl rand -hex 32)

install -d -m 0750 -o root -g chan-gateway /etc/chan-gateway

write_env() {
    local path=$1 content=$2 backup
    if [[ -f "$path" ]]; then
        backup="${path}.bak.$(date +%Y%m%d-%H%M%S)"
        cp -p "$path" "$backup"
        echo "backed up $path -> $backup"
    fi
    install -m 0640 -o root -g chan-gateway /dev/stdin "$path" <<< "$content"
    echo "wrote $path"
}

write_env /etc/chan-gateway/domain.env "$(cat <<EOF
# Generated by configure.sh on $(date -Iseconds).
# Shared domain config; identity + workspace-proxy derive their public
# hostnames from CHAN_DOMAIN and their URL scheme from PUBLIC_SCHEME.
CHAN_DOMAIN=${CHAN_DOMAIN}
PUBLIC_SCHEME=${PUBLIC_SCHEME}
EOF
)"

write_env /etc/chan-gateway/profile.env "$(cat <<EOF
# Generated by configure.sh on $(date -Iseconds).
BIND_ADDR=127.0.0.1:7001
DATABASE_URL=${DATABASE_URL}
PROFILE_AUTH_TOKEN=${PROFILE_AUTH_TOKEN}
EOF
)"

PROVIDER_ENV=$(
    {
        emit_provider_env GITHUB    "$GH_ID"   "$GH_SECRET"
        emit_provider_env GOOGLE    "$GOOG_ID" "$GOOG_SECRET"
        emit_provider_env GITLAB    "$GL_ID"   "$GL_SECRET"
    }
)

write_env /etc/chan-gateway/identity.env "$(cat <<EOF
# Generated by configure.sh on $(date -Iseconds).
BIND_ADDR=127.0.0.1:7000
DATABASE_URL=${DATABASE_URL}
COOKIE_SECURE=true
PROFILE_SERVICE_URL=http://127.0.0.1:7001
PROFILE_AUTH_TOKEN=${PROFILE_AUTH_TOKEN}
${PROVIDER_ENV}
EOF
)"

# NOTE: this block is stale relative to the post-refactor
# workspace-proxy (it predates the workspace-gate rework). It still
# emits DATABASE_URL / REGISTRY_TOKEN, which the current binary does
# not read, and omits the now-required IDENTITY_URL,
# IDENTITY_INTERNAL_TOKEN, and WORKSPACE_GATE_SECRET. Reconciling the
# full env contract is tracked separately; only the domain handling is
# updated here (hostnames now come from domain.env).
write_env /etc/chan-gateway/workspace-proxy.env "$(cat <<EOF
# Generated by configure.sh on $(date -Iseconds).
BIND_ADDR=127.0.0.1:7002
DATABASE_URL=${DATABASE_URL}
COOKIE_SECURE=true
PROFILE_SERVICE_URL=http://127.0.0.1:7001
PROFILE_AUTH_TOKEN=${PROFILE_AUTH_TOKEN}
REGISTRY_TOKEN=${REGISTRY_TOKEN}
EOF
)"

echo
echo "Done. Verify each enabled OAuth app's Authorization callback URL is:"
[[ -n "$GH_ID"   ]] && echo "    ${ID_URL}/auth/github/callback"
[[ -n "$GOOG_ID" ]] && echo "    ${ID_URL}/auth/google/callback"
[[ -n "$GL_ID"   ]] && echo "    ${ID_URL}/auth/gitlab/callback"
echo
echo "Then enable + start the services:"
echo "    systemctl enable --now chan-gateway-profile"
echo "    systemctl enable --now chan-gateway-identity"
echo "    systemctl enable --now chan-gateway-workspace-proxy"
echo
echo "Tail logs while bringing them up:"
echo "    journalctl -u 'chan-gateway-*' -f"
