#!/usr/bin/env bash
# Generate /etc/chan-gateway/{domain,profile,identity,devserver-proxy,
# admin}.env on a host where the .debs are already installed.
#
# Usage:
#   sudo ./configure.sh
#
# Prompts for the values that aren't safely defaultable (Postgres
# password, base domain, OAuth credentials). Generates the shared
# secrets (PROFILE_AUTH_TOKEN, IDENTITY_INTERNAL_TOKEN,
# DEVSERVER_GATE_SECRET, and one admin token wired as
# PROFILE_ADMIN_TOKEN / DEVSERVER_ADMIN_TOKEN / CHAN_ADMIN_TOKEN) and
# threads them across the files where they must match. Backs up any
# existing env files before overwriting.

set -euo pipefail

if [[ $EUID -ne 0 ]]; then
    echo "error: run as root (sudo $0)" >&2
    exit 1
fi

if ! getent passwd chan-gateway >/dev/null; then
    echo "error: chan-gateway user is missing. Install the .debs first." >&2
    exit 1
fi

read -rp "Postgres user [chan]: " PG_USER
PG_USER=${PG_USER:-chan}

read -rsp "Postgres password for ${PG_USER}: " PG_PASS; echo
[[ -n "$PG_PASS" ]] || { echo "password required" >&2; exit 1; }

read -rp "Postgres database [chan_gateway]: " PG_DB
PG_DB=${PG_DB:-chan_gateway}

read -rp "Gateway public origin [https://gw.chan.app]: " ID_URL
ID_URL=${ID_URL:-https://gw.chan.app}
read -rp "Proxy namespace origin [https://usr.chan.app]: " PROXY_ORIGIN
PROXY_ORIGIN=${PROXY_ORIGIN:-https://usr.chan.app}
read -rp "Tunnel ingress origin [$PROXY_ORIGIN]: " TUNNEL_ORIGIN
TUNNEL_ORIGIN=${TUNNEL_ORIGIN:-$PROXY_ORIGIN}
read -rp "This proxy node origin [$PROXY_ORIGIN]: " PROXY_BASE_URL
PROXY_BASE_URL=${PROXY_BASE_URL:-$PROXY_ORIGIN}

echo
echo "Configure at least one OAuth provider. Press Enter to skip any."
echo

# shellcheck disable=SC2034  # namerefs: the writes land in the caller's vars
prompt_provider() {
    # bash 4.3+ namerefs; safer than `eval` because the value never
    # passes through the shell parser.
    local name=$1
    local -n out_id=$2
    local -n out_secret=$3
    local id="" secret=""
    read -rp "$name OAuth Client ID (empty to skip): " id
    if [[ -n "$id" ]]; then
        read -rsp "$name OAuth Client Secret: " secret; echo
        if [[ -z "$secret" ]]; then
            echo "  -> ${name} secret was empty; skipping ${name}"
            id=""
        fi
    fi
    out_id="$id"
    out_secret="$secret"
}

prompt_provider "GitHub"     GH_ID  GH_SECRET
prompt_provider "Google"     GOOG_ID GOOG_SECRET
prompt_provider "GitLab"     GL_ID  GL_SECRET

if [[ -z "$GH_ID" && -z "$GOOG_ID" && -z "$GL_ID" ]]; then
    echo "error: at least one provider is required" >&2
    exit 1
fi

emit_provider_env() {
    local prefix=$1 id=$2 secret=$3
    if [[ -n "$id" ]]; then
        printf '%s_CLIENT_ID=%s\n%s_CLIENT_SECRET=%s\n' \
            "$prefix" "$id" "$prefix" "$secret"
    fi
}

# URL-encode the password so special characters don't break DATABASE_URL.
PG_PASS_ENC=$(python3 -c 'import sys,urllib.parse; print(urllib.parse.quote(sys.argv[1], safe=""))' "$PG_PASS")
DATABASE_URL="postgres://${PG_USER}:${PG_PASS_ENC}@127.0.0.1/${PG_DB}"

# Shared secrets. The admin token is one value wired into three vars
# that must match: profile's PROFILE_ADMIN_TOKEN, devserver-proxy's
# DEVSERVER_ADMIN_TOKEN, and the operator's CHAN_ADMIN_TOKEN.
# IDENTITY_INTERNAL_TOKEN and DEVSERVER_GATE_SECRET are each shared by
# exactly two services (identity <-> devserver-proxy).
PROFILE_AUTH_TOKEN=$(openssl rand -hex 32)
IDENTITY_INTERNAL_TOKEN=$(openssl rand -hex 32)
DEVSERVER_GATE_SECRET=$(openssl rand -hex 32)
ADMIN_TOKEN=$(openssl rand -hex 32)

install -d -m 0750 -o root -g chan-gateway /etc/chan-gateway

write_env() {
    local path=$1 content=$2 backup
    if [[ -f "$path" ]]; then
        backup="${path}.bak.$(date +%Y%m%d-%H%M%S)"
        cp -p "$path" "$backup"
        echo "backed up $path -> $backup"
    fi
    # Write via a redirect, not `install /dev/stdin`: GNU install fails
    # with "No such file or directory" reading the here-string fd when
    # the destination already exists (and the .debs ship these as
    # conf-files, so it always does). Set owner/mode explicitly after.
    printf '%s\n' "$content" > "$path"
    chown root:chan-gateway "$path"
    chmod 0640 "$path"
    echo "wrote $path"
}

write_env /etc/chan-gateway/domain.env "$(cat <<EOF
# Generated by configure.sh on $(date -Iseconds).
# Explicit public origins. No service derives deployment hostnames.
BASE_URL=${ID_URL}
DEVSERVER_PROXY_ORIGIN=${PROXY_ORIGIN}
DEVSERVER_TUNNEL_ORIGIN=${TUNNEL_ORIGIN}
DEVSERVER_PROXY_BASE_URL=${PROXY_BASE_URL}
DASHBOARD_URL=${ID_URL}/workspaces
EOF
)"

write_env /etc/chan-gateway/profile.env "$(cat <<EOF
# Generated by configure.sh on $(date -Iseconds).
BIND_ADDR=127.0.0.1:7001
DATABASE_URL=${DATABASE_URL}
PROFILE_AUTH_TOKEN=${PROFILE_AUTH_TOKEN}
PROFILE_ADMIN_TOKEN=${ADMIN_TOKEN}
DEVSERVER_ADMIN_URL=http://127.0.0.1:7002
DEVSERVER_ADMIN_TOKEN=${ADMIN_TOKEN}
EOF
)"

PROVIDER_ENV=$(
    {
        emit_provider_env GITHUB    "$GH_ID"   "$GH_SECRET"
        emit_provider_env GOOGLE    "$GOOG_ID" "$GOOG_SECRET"
        emit_provider_env GITLAB    "$GL_ID"   "$GL_SECRET"
    }
)

write_env /etc/chan-gateway/identity.env "$(cat <<EOF
# Generated by configure.sh on $(date -Iseconds).
BIND_ADDR=127.0.0.1:7000
DATABASE_URL=${DATABASE_URL}
COOKIE_SECURE=true
PROFILE_SERVICE_URL=http://127.0.0.1:7001
PROFILE_AUTH_TOKEN=${PROFILE_AUTH_TOKEN}
IDENTITY_INTERNAL_TOKEN=${IDENTITY_INTERNAL_TOKEN}
DEVSERVER_GATE_SECRET=${DEVSERVER_GATE_SECRET}
DEVSERVER_ADMIN_URL=http://127.0.0.1:7002
DEVSERVER_ADMIN_TOKEN=${ADMIN_TOKEN}
${PROVIDER_ENV}
EOF
)"

write_env /etc/chan-gateway/devserver-proxy.env "$(cat <<EOF
# Generated by configure.sh on $(date -Iseconds).
# devserver-proxy holds no database; hostnames come from domain.env.
BIND_ADDR=127.0.0.1:7002
TUNNEL_BIND_ADDR=127.0.0.1:7100
IDENTITY_URL=http://127.0.0.1:7000
IDENTITY_INTERNAL_TOKEN=${IDENTITY_INTERNAL_TOKEN}
DEVSERVER_GATE_SECRET=${DEVSERVER_GATE_SECRET}
DEVSERVER_ADMIN_TOKEN=${ADMIN_TOKEN}
MAX_WORKSPACES_PER_USER=0
EOF
)"

write_env /etc/chan-gateway/admin.env "$(cat <<EOF
# Generated by configure.sh on $(date -Iseconds).
CHAN_ADMIN_PROFILE_URL=http://127.0.0.1:7001
CHAN_ADMIN_WORKSPACE_URL=http://127.0.0.1:7002
CHAN_ADMIN_TOKEN=${ADMIN_TOKEN}
EOF
)"

echo
echo "Done. Verify each enabled OAuth app's Authorization callback URL is:"
[[ -n "$GH_ID"   ]] && echo "    ${ID_URL}/auth/github/callback"
[[ -n "$GOOG_ID" ]] && echo "    ${ID_URL}/auth/google/callback"
[[ -n "$GL_ID"   ]] && echo "    ${ID_URL}/auth/gitlab/callback"
echo
echo "Then enable + start the services:"
echo "    systemctl enable --now chan-gateway-profile"
echo "    systemctl enable --now chan-gateway-identity"
echo "    systemctl enable --now chan-gateway-devserver-proxy"
echo
echo "Tail logs while bringing them up:"
echo "    journalctl -u 'chan-gateway-*' -f"
