#!/bin/sh
set -e

case "$1" in
  configure)
    if ! getent passwd chan-gateway >/dev/null; then
      adduser --system --no-create-home --group chan-gateway
    fi
    install -d -m 0750 -o root -g chan-gateway /etc/chan-gateway
    if [ -f /etc/chan-gateway/devserver-proxy.env ]; then
      chown root:chan-gateway /etc/chan-gateway/devserver-proxy.env
      chmod 0640 /etc/chan-gateway/devserver-proxy.env
    fi
    ;;
esac

#DEBHELPER#

exit 0
