#!/usr/bin/env bash
# packaging/gateway/scripts/dev/setup.sh
#
# One-time bootstrap for the local dev stack:
#   * Generates secrets in packaging/gateway/scripts/dev/secrets/*.env if missing.
#   * Validates that packaging/gateway/scripts/dev/.env has the GitHub OAuth creds.
#   * Confirms Postgres is reachable and runs profile-service once
#     with --check (so migrations apply before run.sh starts the
#     long-lived services).
#
# Idempotent. Pass --force to regenerate secrets from scratch.

set -euo pipefail

cd "$(dirname "$0")"
SCRIPT_DIR="$(pwd -P)"
SECRETS_DIR="$SCRIPT_DIR/secrets"
ENV_FILE="$SCRIPT_DIR/.env"
ROOT="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel)/gateway"

FORCE=0
for arg in "$@"; do
    case "$arg" in
        -f|--force) FORCE=1 ;;
        -h|--help)
            sed -n '2,12p' "$0" | sed 's/^# \?//'
            exit 0
            ;;
        *) echo "unknown arg: $arg" >&2; exit 2 ;;
    esac
done

if [[ ! -f "$ENV_FILE" ]]; then
    echo "error: $ENV_FILE missing; copy env.example and fill in GITHUB_CLIENT_ID + GITHUB_CLIENT_SECRET" >&2
    exit 1
fi
# shellcheck disable=SC1090
set -a; . "$ENV_FILE"; set +a

if [[ -z "${GITHUB_CLIENT_ID:-}" || -z "${GITHUB_CLIENT_SECRET:-}" ]]; then
    echo "error: GITHUB_CLIENT_ID and GITHUB_CLIENT_SECRET must be set in $ENV_FILE" >&2
    echo "       (see env.example for how to provision a dev OAuth app)" >&2
    exit 1
fi

DATABASE_URL=${DATABASE_URL:-postgres://chan:chan@127.0.0.1/chan_gateway}

mkdir -p "$SECRETS_DIR"

# Generate secrets if absent (or always if --force).
get_existing() {
    local path=$1 key=$2
    [[ -f "$path" ]] || return 1
    awk -F= -v k="$key" '$1==k {sub(/^[^=]+=/,""); print; exit}' "$path"
}

rand_hex() { openssl rand -hex 32; }

PROFILE_AUTH_TOKEN=$(get_existing "$SECRETS_DIR/profile.env" PROFILE_AUTH_TOKEN || true)
[[ -z "$PROFILE_AUTH_TOKEN" || $FORCE -eq 1 ]] && PROFILE_AUTH_TOKEN=$(rand_hex)

PROFILE_ADMIN_TOKEN=$(get_existing "$SECRETS_DIR/profile.env" PROFILE_ADMIN_TOKEN || true)
[[ -z "$PROFILE_ADMIN_TOKEN" || $FORCE -eq 1 ]] && PROFILE_ADMIN_TOKEN=$(rand_hex)

IDENTITY_INTERNAL_TOKEN=$(get_existing "$SECRETS_DIR/identity.env" IDENTITY_INTERNAL_TOKEN || true)
[[ -z "$IDENTITY_INTERNAL_TOKEN" || $FORCE -eq 1 ]] && IDENTITY_INTERNAL_TOKEN=$(rand_hex)

DEVSERVER_GATE_SECRET=$(get_existing "$SECRETS_DIR/identity.env" DEVSERVER_GATE_SECRET || true)
[[ -z "$DEVSERVER_GATE_SECRET" || $FORCE -eq 1 ]] && DEVSERVER_GATE_SECRET=$(rand_hex)

write_env() {
    local path=$1 content=$2
    if [[ -f "$path" && $FORCE -eq 0 ]]; then
        # Re-emit anyway so a manual edit gets overwritten back to
        # a self-consistent state. Use --force when you actually
        # want to keep manual edits out of the loop.
        :
    fi
    printf '%s\n' "$content" > "$path"
    chmod 0600 "$path"
}

write_env "$SECRETS_DIR/profile.env" "# generated by packaging/gateway/scripts/dev/setup.sh
BIND_ADDR=127.0.0.1:17001
DATABASE_URL=$DATABASE_URL
PROFILE_AUTH_TOKEN=$PROFILE_AUTH_TOKEN
PROFILE_ADMIN_TOKEN=$PROFILE_ADMIN_TOKEN
DEVSERVER_ADMIN_URL=http://127.0.0.1:17002
DEVSERVER_ADMIN_TOKEN=$PROFILE_ADMIN_TOKEN
RUST_LOG=${RUST_LOG:-info,profile=debug}"

PROVIDER_ENV="GITHUB_CLIENT_ID=$GITHUB_CLIENT_ID
GITHUB_CLIENT_SECRET=$GITHUB_CLIENT_SECRET"
if [[ -n "${GOOGLE_CLIENT_ID:-}" ]]; then
    PROVIDER_ENV+="
GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET"
fi
if [[ -n "${GITLAB_CLIENT_ID:-}" ]]; then
    PROVIDER_ENV+="
GITLAB_CLIENT_ID=$GITLAB_CLIENT_ID
GITLAB_CLIENT_SECRET=$GITLAB_CLIENT_SECRET"
fi

write_env "$SECRETS_DIR/identity.env" "# generated by packaging/gateway/scripts/dev/setup.sh
BIND_ADDR=127.0.0.1:17000
BASE_URL=http://id.localtest.me:17000
DATABASE_URL=$DATABASE_URL
COOKIE_SECURE=false
PROFILE_SERVICE_URL=http://127.0.0.1:17001
PROFILE_AUTH_TOKEN=$PROFILE_AUTH_TOKEN
IDENTITY_INTERNAL_TOKEN=$IDENTITY_INTERNAL_TOKEN
DEVSERVER_ADMIN_URL=http://127.0.0.1:17002
DEVSERVER_ADMIN_TOKEN=$PROFILE_ADMIN_TOKEN
DEVSERVER_GATE_SECRET=$DEVSERVER_GATE_SECRET
# Single source for the domain: derives id.localtest.me and
# .devserver.localtest.me. PUBLIC_SCHEME drives the workspace redirect
# scheme too. Only the dev port still needs an explicit override.
CHAN_DOMAIN=localtest.me
PUBLIC_SCHEME=http
DEVSERVER_PUBLIC_PORT=:17002
$PROVIDER_ENV
RUST_LOG=${RUST_LOG:-info,identity=debug}"

write_env "$SECRETS_DIR/devserver-proxy.env" "# generated by packaging/gateway/scripts/dev/setup.sh
BIND_ADDR=127.0.0.1:17002
TUNNEL_BIND_ADDR=127.0.0.1:17100
# Single source for the domain: derives the devserver.localtest.me apex
# and the .devserver.localtest.me wildcard. DASHBOARD_URL is still set
# explicitly because the derived id host carries no dev port.
CHAN_DOMAIN=localtest.me
PUBLIC_SCHEME=http
DASHBOARD_URL=http://id.localtest.me:17000/workspaces
IDENTITY_URL=http://127.0.0.1:17000
IDENTITY_INTERNAL_TOKEN=$IDENTITY_INTERNAL_TOKEN
DEVSERVER_GATE_SECRET=$DEVSERVER_GATE_SECRET
DEVSERVER_ADMIN_TOKEN=$PROFILE_ADMIN_TOKEN
MAX_WORKSPACES_PER_USER=4
RUST_LOG=${RUST_LOG:-info,devserver_proxy=debug}"

echo "wrote secrets to $SECRETS_DIR/"

# Apply migrations by starting profile-service briefly. It runs the
# sqlx migrate on boot and then blocks on the listener; we wait for
# /healthz then SIGINT it. Doing this here gives setup.sh a clear
# success/failure signal; run.sh later starts profile + identity +
# devserver-proxy together and skips the wait.
echo "applying migrations via profile-service..."
(
    cd "$ROOT"
    cargo build --quiet --bin profile-service
    env DATABASE_URL="$DATABASE_URL" \
        PROFILE_AUTH_TOKEN="$PROFILE_AUTH_TOKEN" \
        PROFILE_ADMIN_TOKEN="$PROFILE_ADMIN_TOKEN" \
        BIND_ADDR=127.0.0.1:17099 \
        ./target/debug/profile-service >/tmp/chan-dev-migrate.log 2>&1 &
    pid=$!
    ok=0
    for _ in $(seq 1 60); do
        if curl -sf http://127.0.0.1:17099/healthz >/dev/null 2>&1; then
            ok=1
            break
        fi
        sleep 0.5
    done
    kill -INT "$pid" 2>/dev/null || true
    wait "$pid" 2>/dev/null || true
    if (( ok == 0 )); then
        echo "error: profile-service did not become healthy; see /tmp/chan-dev-migrate.log" >&2
        exit 1
    fi
)

echo
echo "setup complete."
echo "  next: packaging/gateway/scripts/dev/run.sh"
