#!/usr/bin/env bash
# packaging/gateway/scripts/dev/setup.sh
#
# One-time bootstrap for the local dev stack:
#   * Generates secrets in packaging/gateway/scripts/dev/secrets/*.env if missing.
#   * Validates that packaging/gateway/scripts/dev/.env has the GitHub OAuth creds.
#   * Confirms Postgres is reachable and runs profile-service once
#     with --check (so migrations apply before run.sh starts the
#     long-lived services).
#
# Idempotent. Pass --force to regenerate secrets from scratch.

set -euo pipefail

cd "$(dirname "$0")"
SCRIPT_DIR="$(pwd -P)"
SECRETS_DIR="$SCRIPT_DIR/secrets"
ENV_FILE="$SCRIPT_DIR/.env"
ROOT="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel)/gateway"

FORCE=0
for arg in "$@"; do
    case "$arg" in
        -f|--force) FORCE=1 ;;
        -h|--help)
            sed -n '2,12p' "$0" | sed 's/^# \?//'
            exit 0
            ;;
        *) echo "unknown arg: $arg" >&2; exit 2 ;;
    esac
done

if [[ ! -f "$ENV_FILE" ]]; then
    echo "error: $ENV_FILE missing; copy env.example and fill in GITHUB_CLIENT_ID + GITHUB_CLIENT_SECRET" >&2
    exit 1
fi
set -a
# $ENV_FILE is a developer's own secrets file, chosen at runtime and never
# checked in, so there is no path for shellcheck to follow.
# shellcheck source=/dev/null
. "$ENV_FILE"
set +a

if [[ -z "${GITHUB_CLIENT_ID:-}" || -z "${GITHUB_CLIENT_SECRET:-}" ]]; then
    echo "error: GITHUB_CLIENT_ID and GITHUB_CLIENT_SECRET must be set in $ENV_FILE" >&2
    echo "       (see env.example for how to provision a dev OAuth app)" >&2
    exit 1
fi

DATABASE_URL=${DATABASE_URL:-postgres://chan:chan@127.0.0.1/chan_gateway}

mkdir -p "$SECRETS_DIR"

# Generate secrets if absent (or always if --force).
get_existing() {
    local path=$1 key=$2
    [[ -f "$path" ]] || return 1
    awk -F= -v k="$key" '$1==k {sub(/^[^=]+=/,""); print; exit}' "$path"
}

rand_hex() { openssl rand -hex 32; }

PROFILE_AUTH_TOKEN=$(get_existing "$SECRETS_DIR/profile.env" PROFILE_AUTH_TOKEN || true)
[[ -z "$PROFILE_AUTH_TOKEN" || $FORCE -eq 1 ]] && PROFILE_AUTH_TOKEN=$(rand_hex)

PROFILE_ADMIN_TOKEN=$(get_existing "$SECRETS_DIR/profile.env" PROFILE_ADMIN_TOKEN || true)
[[ -z "$PROFILE_ADMIN_TOKEN" || $FORCE -eq 1 ]] && PROFILE_ADMIN_TOKEN=$(rand_hex)

IDENTITY_INTERNAL_TOKEN=$(get_existing "$SECRETS_DIR/identity.env" IDENTITY_INTERNAL_TOKEN || true)
[[ -z "$IDENTITY_INTERNAL_TOKEN" || $FORCE -eq 1 ]] && IDENTITY_INTERNAL_TOKEN=$(rand_hex)

DEVSERVER_GATE_SECRET=$(get_existing "$SECRETS_DIR/identity.env" DEVSERVER_GATE_SECRET || true)
[[ -z "$DEVSERVER_GATE_SECRET" || $FORCE -eq 1 ]] && DEVSERVER_GATE_SECRET=$(rand_hex)

DEVSERVER_ADMIN_TOKEN=$(get_existing "$SECRETS_DIR/devserver-control.env" DEVSERVER_ADMIN_TOKEN || true)
[[ -z "$DEVSERVER_ADMIN_TOKEN" || $FORCE -eq 1 ]] && DEVSERVER_ADMIN_TOKEN=$(rand_hex)

DEVSERVER_PROXY_TOKEN=$(get_existing "$SECRETS_DIR/devserver-control.env" DEVSERVER_PROXY_TOKEN || true)
[[ -z "$DEVSERVER_PROXY_TOKEN" || $FORCE -eq 1 ]] && DEVSERVER_PROXY_TOKEN=$(rand_hex)

write_env() {
    local path=$1 content=$2
    if [[ -f "$path" && $FORCE -eq 0 ]]; then
        # Re-emit anyway so a manual edit gets overwritten back to
        # a self-consistent state. Use --force when you actually
        # want to keep manual edits out of the loop.
        :
    fi
    printf '%s\n' "$content" > "$path"
    chmod 0600 "$path"
}

write_env "$SECRETS_DIR/profile.env" "# generated by packaging/gateway/scripts/dev/setup.sh
BIND_ADDR=127.0.0.1:17001
DATABASE_URL=$DATABASE_URL
PROFILE_AUTH_TOKEN=$PROFILE_AUTH_TOKEN
PROFILE_ADMIN_TOKEN=$PROFILE_ADMIN_TOKEN
DEVSERVER_ADMIN_URL=http://127.0.0.1:17003
DEVSERVER_ADMIN_TOKEN=$DEVSERVER_ADMIN_TOKEN
RUST_LOG=${RUST_LOG:-info,profile=debug}"

PROVIDER_ENV="GITHUB_CLIENT_ID=$GITHUB_CLIENT_ID
GITHUB_CLIENT_SECRET=$GITHUB_CLIENT_SECRET"
# A provider configured with an id but no secret is a half-written env file:
# name the missing variable instead of aborting on `set -u`.
if [[ -n "${GOOGLE_CLIENT_ID:-}" ]]; then
    PROVIDER_ENV+="
GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:?set GOOGLE_CLIENT_SECRET alongside GOOGLE_CLIENT_ID}"
fi
if [[ -n "${GITLAB_CLIENT_ID:-}" ]]; then
    PROVIDER_ENV+="
GITLAB_CLIENT_ID=$GITLAB_CLIENT_ID
GITLAB_CLIENT_SECRET=${GITLAB_CLIENT_SECRET:?set GITLAB_CLIENT_SECRET alongside GITLAB_CLIENT_ID}"
fi

write_env "$SECRETS_DIR/identity.env" "# generated by packaging/gateway/scripts/dev/setup.sh
BIND_ADDR=127.0.0.1:17000
BASE_URL=http://id.localtest.me:17000
DEVSERVER_PROXY_ORIGIN=http://devserver.localtest.me:17002
DEVSERVER_TUNNEL_ORIGIN=http://devserver.localtest.me:17100
DATABASE_URL=$DATABASE_URL
COOKIE_SECURE=false
PROFILE_SERVICE_URL=http://127.0.0.1:17001
PROFILE_AUTH_TOKEN=$PROFILE_AUTH_TOKEN
IDENTITY_INTERNAL_TOKEN=$IDENTITY_INTERNAL_TOKEN
DEVSERVER_ADMIN_URL=http://127.0.0.1:17003
DEVSERVER_ADMIN_TOKEN=$DEVSERVER_ADMIN_TOKEN
DEVSERVER_GATE_SECRET=$DEVSERVER_GATE_SECRET
$PROVIDER_ENV
RUST_LOG=${RUST_LOG:-info,identity=debug}"

# The controller owns the aggregate admin tree and fleet admission;
# identity and profile point their DEVSERVER_ADMIN_URL at it. Its
# origin template pins every proxy's public base URL to one node label
# below the devserver apex.
write_env "$SECRETS_DIR/devserver-control.env" "# generated by packaging/gateway/scripts/dev/setup.sh
BIND_ADDR=127.0.0.1:17003
PROXY_BIND_ADDR=127.0.0.1:17101
DEVSERVER_ADMIN_TOKEN=$DEVSERVER_ADMIN_TOKEN
DEVSERVER_PROXY_TOKEN=$DEVSERVER_PROXY_TOKEN
DEVSERVER_PROXY_BASE_URL_TEMPLATE=http://{proxy_id}.devserver.localtest.me:17002
RUST_LOG=${RUST_LOG:-info,devserver_control=debug}"

# One env file per proxy node so run.sh can boot a fleet of 1 to 3.
# p1 keeps the historical 127.0.0.1 ports so the single-proxy default
# is unchanged; p2/p3 take the same ports on 127.0.0.2/127.0.0.3
# (loopback aliases) because the origin template cannot express a
# per-node port.
rm -f "$SECRETS_DIR/devserver-proxy.env"
for n in 1 2 3; do
    write_env "$SECRETS_DIR/devserver-proxy.p$n.env" "# generated by packaging/gateway/scripts/dev/setup.sh
BIND_ADDR=127.0.0.$n:17002
TUNNEL_BIND_ADDR=127.0.0.$n:17100
DEVSERVER_TUNNEL_ORIGIN=http://devserver.localtest.me:17100
DEVSERVER_PROXY_BASE_URL=http://p$n.devserver.localtest.me:17002
DEVSERVER_CONTROL_URL=http://127.0.0.1:17101
DEVSERVER_PROXY_TOKEN=$DEVSERVER_PROXY_TOKEN
DEVSERVER_PROXY_ID=p$n
DASHBOARD_URL=http://id.localtest.me:17000/workspaces
IDENTITY_URL=http://127.0.0.1:17000
IDENTITY_INTERNAL_TOKEN=$IDENTITY_INTERNAL_TOKEN
DEVSERVER_GATE_SECRET=$DEVSERVER_GATE_SECRET
FORWARDED_PROTO=http
RUST_LOG=${RUST_LOG:-info,devserver_proxy=debug}"
done

echo "wrote secrets to $SECRETS_DIR/"

# Apply migrations by starting profile-service briefly. It runs the
# sqlx migrate on boot and then blocks on the listener; we wait for
# /healthz then SIGINT it. Doing this here gives setup.sh a clear
# success/failure signal; run.sh later starts profile + identity +
# devserver-proxy together and skips the wait.
echo "applying migrations via profile-service..."
(
    cd "$ROOT"
    cargo build --quiet --bin profile-service
    env DATABASE_URL="$DATABASE_URL" \
        PROFILE_AUTH_TOKEN="$PROFILE_AUTH_TOKEN" \
        PROFILE_ADMIN_TOKEN="$PROFILE_ADMIN_TOKEN" \
        BIND_ADDR=127.0.0.1:17099 \
        ./target/debug/profile-service >/tmp/chan-dev-migrate.log 2>&1 &
    pid=$!
    ok=0
    for _ in $(seq 1 60); do
        if curl -sf http://127.0.0.1:17099/healthz >/dev/null 2>&1; then
            ok=1
            break
        fi
        sleep 0.5
    done
    kill -INT "$pid" 2>/dev/null || true
    wait "$pid" 2>/dev/null || true
    if (( ok == 0 )); then
        echo "error: profile-service did not become healthy; see /tmp/chan-dev-migrate.log" >&2
        exit 1
    fi
)

echo
echo "setup complete."
echo "  next: packaging/gateway/scripts/dev/run.sh"
